### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by srknzl** [rubo77/set_resolution.py#11]
Hi, Getting : 
Traceback (most recent call last):
  File "autoRes.py", line 84, in <module>
    if currentWindow != check_frontmost():  # test for change
  File "autoRes.py", line 39, in check_frontmost
    windowName = execute("xdotool getactivewindow getwindowname").lower()
AttributeError: 'NoneType' object has no attribute 'lower'

My solution is to add time.sleep(1.0) just before
 windowName = execute("xdotool getactivewindow getwindowname").lower(),
because when a window is closed it could not adapt as fast as needed. Do you think adapting this change to the code? 

Thanks 

EDIT: I have also checked if windowName is str because sometimes it is not and cause errors in the next line.

**Comment by Houndoom96** [comment]
Is is this for Xorg or Wayland, I think my issues is that I am using Wayland?

Traceback (most recent call last):
  File "./set_resolution.py", line 80, in <module>
    currentWindow = check_frontmost()  # get front window
  File "./set_resolution.py", line 37, in check_frontmost
    windowName = execute("xdotool getactivewindow getwindowname").lower()
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by rubo77** [comment]
@srknzl why did you close this?

**Comment by Jacob-Vlijm** [comment]
@rubo77  Because, as he sais, he is using wayland. xdotool <> wayland.

**Comment by srknzl** [comment]
Because of no activity
